// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sekajdejjchxsjrltbrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNla2FqZGVqamNoeHNqcmx0YnJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODkzODksImV4cCI6MjA2MzY2NTM4OX0.1LnSq8ieaUKoUgMLa88TBNw4ujhj8x2gBQNyzocCBng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);